{% set name = "tgtools" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}
source:
  url: https://github.com/jodyphelan/tgtools/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ea13088b785effcd033e2021d12fdcc01ea35f63cdc3bedc6d4353674bcab0d2

requirements:
  build:
    - python
    - flit
    - pip
  run:
    - python
    - tqdm
    - pydantic

run_exports:
  - pydantic >=2.0,<3.0

test:
  commands:
    - tgtools --help
    - tgtools import --help
    - tgtools import snp-distance --help


about:
  home: https://github.com/jodyphelan/tgtools
  license: MIT
  license_file: LICENSE
  summary: "Tool to manipulate transmission network JSON (transjson) files."

extra:
  recipe-maintainers:
    - buhlentozini
